- name: install needed packages
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - php7.0
    - php7.0-mysql
    - php7.0-ldap
    - php7.0-redis
    - apache2
    - libapache2-mod-php7.0
    - vim
    - mc
    - needrestart