concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-worker"
  url = "%GITLAB_HOST%"
  token = "%TOKEN_SHELL%"
  executor = "shell"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "docker-worker"
  url = "%GITLAB_HOST%"
  token = "%TOKEN_DOCKER%"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "debian:stretch-slim"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
