---
# - hosts:
    # - masters
    # - workers
  # roles:
    # - kernel

# - hosts:
#    - masters
#    - workers
#    - lbs
#   roles:
#    - common

# - hosts:
#    - masters
#    - workers
#   roles:
#     - dkr_kublet

# - hosts: lbs
#   roles:
#     - lb

- hosts: masters
  roles:
    - master

- hosts: workers
  roles:
    - worker