---

# ==================================
# system config
# ==================================
- name: Configure firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10255/tcp
  notify: Reload firewalld

# ==================================
# k8s init
# ==================================

- name: Check for admin.conf exists in /etc/kubernetes     
  stat: 
    path: /etc/kubernetes/admin.conf
  register: p

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr={{ k8s_net }} >> cluster_initialized.txt
  args:
    chdir: /root
    creates: /etc/kubernetes/admin.conf
  when: not p.stat.exists

- name: Create .kube directory
  become: yes
  become_user: root
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    remote_src: yes
    owner: root

- name: Get k8s version
  shell: "kubectl version | base64 | tr -d '\n'"
  register: k8s_version

- name: Init k8s network
  command: >
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ k8s_version.stdout }}"

- name: Get join command
  command: >
    kubeadm token create --print-join-command
  register: add_to_cluster_cmd
