---
- name: Set hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Rm swapfile from fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Update the /etc/hosts file with node name
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
    backup: yes
  register: etchostsupdate
  when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
  with_items: "{{groups['all']}}"

- name: Disable SELinux
  selinux:
    state: disabled  

- name: Disable selinux permament
  lineinfile:
    dest: "/etc/sysconfig/selinux"
    regexp: "^SELINUX=enforcing"
    line: "SELINUX=disabled"
    state: present

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Enable bridge for iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    state: present
    value: "1"
    reload: yes

- name: Add k8s repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey:
        - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
        - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    enabled: yes

- name: Add docker repo
  yum_repository:
    name: Docker
    description: Docker YUM repo
    file: docker
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install docker and kubeadm
  yum:
    name: 
      - device-mapper-persistent-data 
      - lvm2
      - docker-ce-3:18.09.0-3.el7
      - kubeadm
    state: present

- name: Start and enable kublet
  service:
    name: kubelet
    enabled: yes
    state: restarted

- name: Start and enable docker
  service:
    name: docker
    enabled: yes
    state: restarted

- name: Create docker directories
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Create docker directories
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Copy daemon.json
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json